// src/views/foodSmart/src/components/DateSelect/DateSelect.vue
<template>
	<el-popover popper-class="szl-time-pop" @after-leave="cancel" v-model="show" width="340" trigger="click">
	    <div class="date-container">
	        <div class="date-box">
	            <div class="date-type">
	                <span class="item" @click="changeDateType(1)" :class="{'active' : dateType === 1}">月度</span>
	                <span class="item" @click="changeDateType(4)" :class="{'active' : dateType === 4}">年</span>
	            </div>
	            <div class="date-year">
	                <span class="item prev-year" @click="changeYear('prev')" :class="{'disabled' : currentIndex >= (originDate.length-1)}" >上一年</span>
	                <span class="item current-year">{{ currentYear }}</span>
	                <span class="item next-year" @click="changeYear('next')" :class="{'disabled' : currentIndex <= 0}" >下一年</span>
	            </div>
	            <div class="date-item-box" v-show="currentDate.data">
	                <!-- 日期类型 -->
	                <div class="type-month" v-show="dateType === 1">
	                    <span class="item" v-for="(item, index) in currentDate.data.month" :key="index" :class="{'disabled' : !item.mark, 'active' : index === selectItemIndex}" @click="changeItemStatus(item,index)">{{ item.date }}</span>
	                </div>
	                <div class="type-allyear" v-show="dateType === 4">
	                    <span class="item" v-for="(item, index) in currentDate.data.allYear" :key="index" :class="{'disabled' : !item.mark, 'active' : index === selectItemIndex}" @click="changeItemStatus(item,index)">{{ item.date }}</span>
                    </div>
	            </div>
	            <div class="date-footer">
	                <div class="left">{{ currentTime }}</div>
	                <div class="right">
	                    <span class="btn cancel" @click="cancel()">取消</span>
	                    <span class="btn ok" @click="confirmDate()">确定</span>
	                </div>
	            </div>
	        </div>
	    </div>
    	<div slot="reference" size="small" class="szl-time">
			{{ currentTime }}
			<img :src="require('./images/arrow.png')" alt="" />
		</div>
    </el-popover>
</template>
<script>
import http from '@/unit/http'
import apis from "@/unit/apis"
const {
    LISTDATE,
    FOODWASTE_LISTDATE
} = apis
import originD from '@/unit/originDate.js'
export default {
    data () {
        return {
        	show: false,
            currentTime: "", // 当前时间
            currentIndex: 0,
            dateType: 1,
            originDate: '',
            selectItemIndex: -1,
            platform: ''
        }
    },
    props: ['platFormType'],
	watch: {
		platFormType(platform){
			this.platform = platform
		}
	},
    created () {
        this.originDate = originD.data;
        this.init('normal')
    },
    computed: {
        currentYear () {
            return this.originDate[this.currentIndex].years;
        },
        currentDate () {
        	return this.originDate[this.currentIndex];
        }
    },
    methods: {
        async init (time) {
            let urls = '';
            let res = '';
        	this.dateType = 1;
            // if(this.platFormType == 'netfood'){
            //     urls = LISTDATE;
            //     // res = allDate;
            // }
            // if(this.platFormType == 'foodWaste'){
            //     urls = FOODWASTE_LISTDATE;
            //     // res = allDate1;
            // }
            // res = await http.get(urls);
//          res = allDate;
//          if(res){
//              this.currentIndex = 0;
//              this.originDate = res.data;
//          }
            let month = '';
            for(let j = 0;j < this.originDate.length;j++){
            	for (let i = 11; i > -1; i--) {
	                if (this.originDate[j].data.month[i].mark) {
	                    month = this.originDate[j].data.month[i].date;
	                    this.currentTime = this.currentYear + '年' + month;
	                    this.selectItemIndex = i;
	                    let emitTime = {
	                    	year: this.currentYear,
	                    	msg: month
	                    }
	                    if(this.platFormType == 'netfood'){
	                    	sessionStorage.setItem('netfoodTime', JSON.stringify(emitTime));
	                    	this.$emit("timeChange", emitTime);
	                    }
	                    if(this.platFormType == 'foodWaste'){
                            sessionStorage.setItem('foodWasteTime', JSON.stringify(emitTime));
                            this.$emit("timeChange", emitTime);
                        }
                        if(this.platFormType == 'others'){
                            this.$emit("timeChange", emitTime);
                            console.log(this.currentTime)
                        }
	                    
	                    return false
	                }
	            }
            }
            
        },
        changeYear(flag){
            let index = this.currentIndex;
            if(flag === 'prev') {
                if (index < this.originDate.length-1) {
                	this.selectItemIndex = -1;
                    index++;
                }
            } else {
                if (index > 0) {
                	this.selectItemIndex = -1;
                    index--;
                }
            }
            this.currentIndex = index;
        },
        changeDateType (type) {
            this.dateType = type;
            this.selectItemIndex = -1;
        },
        changeItemStatus (item, index) {
            if (item.mark) {
                this.selectItemIndex = index;
            }
        },
        cancel() {
			this.show = false;
		},
        switchTypeName (i) {
            let name = ''
            switch(i){
                case 1: 
                    name = 'month';
                    break;
                case 2: 
                    name = 'season';
                    break;
                case 3: 
                    name = 'halfYear';
                    break;
                case 4: 
                    name = 'allYear';
                    break;
            }
            return name
        },
        showDateSelect () {
            this.showSelect = !this.showSelect;
        },
        confirmDate () {
        	this.show = false;
            if(this.selectItemIndex == -1){
            	this.dateType = 4;
            	this.selectItemIndex = 0;
            }
            let typeName = this.switchTypeName(this.dateType);
            let dates = this.currentDate.data[typeName][this.selectItemIndex].date
            this.currentTime = this.currentYear + '年' + dates;
            let emitTime = {
            	year: this.currentYear,
            	msg: dates == '全年' ? '': dates
            }
            if(this.platFormType == 'netfood'){
            	sessionStorage.setItem('netfoodTime', JSON.stringify(emitTime));
            }
            if(this.platFormType == 'foodWaste'){
            	sessionStorage.setItem('foodWasteTime', JSON.stringify(emitTime));
            }
            this.$emit("timeChange", emitTime);
            
        }
    },
    mounted () {}
}
</script>
<style lang="scss">
$dateThemeBack: #1c2543;

$dateItemBack: #293458;

$dateActiveBack: #0099FF;

$disableBack: #7E8E98;

$topBack: #2E4354;

$btnOk: #0FA063;

@mixin spanItem($w, $h, $color) {
    display: inline-block;
    height: $h;
    width: $w;
    font-size: 12px;
    color: #ccc;
    line-height: $h;
    box-sizing: border-box;
    text-align: center;
    /*padding-right: 2px;*/
    background: $color;
    margin-top: 2px;
    background-clip: content-box;
    cursor: pointer;
    &.disabled{
        background: $disableBack;
        background-clip: content-box;
        cursor: default;
        color: #ccc;
        &:hover{
            cursor: not-allowed !important;
        }
    }
    &.active{
        background: $dateActiveBack;
        color: #fff;
        background-clip: content-box;
    }
}
.szl-time-pop.el-popper {
	width: 450px;
	background: rgba(28,37,67,1);
	border: 1px solid rgba(28,37,67,1);
	margin-left: 40px;
	padding: 20px;
	* {
		color: #87b3d1;
	}
}

.szl-time {
	display: inline-block;
	background: #0099FF;
	border: 1px solid #0099FF;
	color: #C5E6FE;
	padding: 0 16px;
	height: 32px;
	line-height: 32px;
	cursor: pointer;
	border-radius: 6px;
	img {
		position: relative;
		top: -1px;
		vertical-align: middle;
		opacity: .8;
	}
}

.szl-time-pop.el-popper .popper__arrow {
	border-bottom-color: #253745 !important;
	&:after {
		border-bottom-color: #253745 !important;
	}
}
.date-container{
/*    position: relative;*/
    z-index: 999;
    .date-select{
        width: 100px;
        height: 50px;
        line-height: 50px;
        text-align: center;
    }
    .date-box{
        background: $dateThemeBack;
        /*width: 400px;*/
        height: auto;
        padding: 10px;
        /*position: absolute;*/
        left: 0;
        top: 50px;
        right: 0;
        border-radius: 5px;
        overflow: hidden;
        .date-type{
            width: 100%;
            overflow: hidden;
            background : $topBack;
            margin-right: -2px;
            .item{
                @include spanItem(50%, 32px, $topBack);
                margin-top: 0;
                float: left;
            }
        }
        .date-year{
            width: 100%;
            overflow: hidden;
            margin-top: 8px;
            background: $topBack;
            /*margin-right: -2px;*/
            // margin-top: 6px;
            .item{
                @include spanItem(25%, 32px, $topBack);
                margin-top: 0;
                float: left;
            }
            .current-year{
                @include spanItem(50%, 32px, $topBack);
                margin-top: 0;
                font-size: 14px;
                color: #fff;
                float: left;
            }
        }
        .date-item-box{
            /*width: 100%;*/
            margin-top: 6px;
            margin-right: -2px;
            .item{
            	padding-right: 2px;
            }
            .type-month{
                width: 100%;
                overflow: hidden;
                
                .item{
                    @include spanItem(25%, 32px, $dateItemBack);
                    float: left;
                    
                }
            }
            .type-season{
                width: 100%;
                overflow: hidden;
                /*margin-right: -2px;*/
                .item{
                    @include spanItem(50%, 49px, $dateItemBack);
                    float: left;
                }
            }
            .type-halfyear{
                width: 100%;
                overflow: hidden;
                /*margin-right: -2px;*/
                .item{
                    @include spanItem(50%, 100px, $dateItemBack);
                    float: left;
                }
            }
            .type-allyear{
                width: 100%;
                overflow: hidden;
                /*margin-right: -2px;*/
                .item{
                    @include spanItem(100%, 100px, $dateItemBack);
                    float: left;
                }
            }
        }
        .date-footer{
        	width: 100%;
            overflow: hidden;
            margin-top: 6px;
            .left{
                width: 100px;
                height: 40px;
                line-height: 40px;
                text-align: left;
                float: left;
                color: #fff;
            }
            .right{
                float: right;
                overflow: hidden;
                .btn{
                    @include spanItem(70px, 32px, $dateItemBack);
                    float: left;
                }
                .ok{
                	background: $btnOk;
                }
            }
        }
    }
}
</style>

// src/react/src/component/DateSelect.js
import React, { Component } from 'react'
import { Button, Popover} from 'antd'
import 'antd/dist/antd.css'

import '../styles/dateSelect.scss'
import allDate from '../datas/originDate.js'

// function DateTimebox(prop){
//     // const showBox = prop.
//     console.log(prop);
//     // let htmls = '';
//     if(prop.currentDate.data.length > 0){
//         return (
//             <div className="date-item-box">
//                 {/* <DateTimetype dateType={prop.dateType}/> */}
//             </div>
//         )
//     }
// }
// function DateTimetype(prop){
//     if(prop.dateType === 1){
//         return (
//             <div className="type-month" v-show="dateType === 1">
//                 {
//                     this.state.currentDate.data.month.map((item, i) => (
//                         <span key={i} className={`item ${item.mark ? 'disabled' : ''} ${i === this.state.selectItemIndex ? 'active' : ''}`} onClick={this.changeItemStatus.bind(this,(item,i))}>{ item.date }</span>
//                         // <span className="item" key={i} className={{'disabled' : !item.mark, 'active' : i === this.state.selectItemIndex}} onClick={this.state.changeItemStatus.bind(this,(item,index))}>{ item.date }</span>
//                     ))
//                 }
                
//             </div>
//         )
//     }
//     if(prop.dateType === 4){
//         return (
//             <div className="type-allyear" v-show="dateType === 4">
//                 {
//                     this.state.currentDate.data.allYear.map((item, i) => (
//                         <span key={i} className={`item ${item.mark ? 'disabled' : ''} ${i === this.state.selectItemIndex ? 'active' : ''}`} onClick={this.changeItemStatus.bind(this,(item,i))}>{ item.date }</span>
//                         // <span className="item" key={i} className={{'disabled' : !item.mark, 'active' : i === this.state.selectItemIndex}} onClick={this.state.changeItemStatus.bind(this,(item,index))}>{ item.date }</span>
//                     ))
//                 }
//             </div>
//         )
//     }
    
// }
export default class DateSelect extends Component {
    
    constructor(props){
        super(props)
        this.state = {
            show: false,
            currentTime: "", // 当前时间
            currentIndex: 0,
            dateType: 1,
            originDate: '',
            selectItemIndex: -1,
            platform: '',
            currentDate: '',
            currentYear: ''
        }
    }
    async init (time) {
        let urls = '';
        let res = '';
        this.dateType = 1;
        // if(this.platFormType == 'netfood'){
        //     urls = LISTDATE;
        //     // res = allDate;
        // }
        // if(this.platFormType == 'foodWaste'){
        //     urls = FOODWASTE_LISTDATE;
        //     // res = allDate1;
        // }
        // res = await http.get(urls);
        res = allDate;
        if(res){
            this.currentIndex = 0;
            this.state.originDate = res.data;
        }
        let month = '';
        // console.log(res);
        console.log(this.state.originDate);
        for(let j = 0;j < this.state.originDate.length;j++){
            for (let i = 11; i > -1; i--) {
                if (this.state.originDate[j].data.month[i].mark) {
                    month = this.state.originDate[j].data.month[i].date;
                    // this.currentTime = this.currentYear + '年' + month;
                    // this.selectItemIndex = i;
                    let currentDate = this.state.originDate[this.state.currentIndex];
                    let currentYear = this.state.originDate[this.state.currentIndex].years;
                    this.setState({
                        currentDate: currentDate,
                        currentYear: currentYear
                    })
                    let currenttime = this.state.currentYear + '年' + month;
                    
                    this.setState({
                        currentTime: currenttime,
                        selectItemIndex: i
                    })
                    
                    
                    let emitTime = {
                        year: currentYear,
                        msg: month
                    }
                    console.log(emitTime);
                    console.log(this.state.currentTime);
                    // if(this.platFormType == 'netfood'){
                    //     sessionStorage.setItem('netfoodTime', JSON.stringify(emitTime));
                    //     this.$emit("timeChange", emitTime);
                    // }
                    // if(this.platFormType == 'foodWaste'){
                    //     sessionStorage.setItem('foodWasteTime', JSON.stringify(emitTime));
                    //     this.$emit("timeChange", emitTime);
                    // }
                    // if(this.platFormType == 'others'){
                    //     this.$emit("timeChange", emitTime);
                    // }
                    
                    return false
                }
            }
        }
        
    }
    changeYear(flag){
        let index = this.state.currentIndex;
        if(flag === 'prev') {
            if (index < this.state.originDate.length-1) {
                // this.state.selectItemIndex = -1;
                this.setState({
                    selectItemIndex: -1
                })
                index++;
            }
        } else {
            if (index > 0) {
                // this.state.selectItemIndex = -1;
                this.setState({
                    selectItemIndex: -1
                })
                index--;
            }
        }
        // this.state.currentIndex = index;
        this.setState({
            currentIndex: index
        })
    }
    changeDateType (type) {
        this.setState({
            dateType: type,
            selectItemIndex: -1
        })
        // this.state.dateType = type;
        // this.state.selectItemIndex = -1;
    }
    changeItemStatus (item, index) {
        if (item.mark) {
            // this.state.selectItemIndex = index;
            this.setState({
                selectItemIndex: index
            })
        }
    }
    cancel() {
        // this.state.show = false;
        this.setState({
            show: false
        })
    }
    switchTypeName (i) {
        let name = ''
        switch(i){
            case 1: 
                name = 'month';
                break;
            case 2: 
                name = 'season';
                break;
            case 3: 
                name = 'halfYear';
                break;
            case 4: 
                name = 'allYear';
                break;
            default: 
                return ''
        }
        return name
    }
    showDateSelect () {
        // this.state.showSelect = !this.state.showSelect;
        let showSelect = this.state.showSelect
        this.setState({
            showSelect: !showSelect
        })
    }
    confirmDate () {
        // this.state.show = false;
        // if(this.state.selectItemIndex == -1){
        //     this.state.dateType = 4;
        //     this.state.selectItemIndex = 0;
        // }
        // let typeName = this.state.switchTypeName(this.state.dateType);
        // let dates = this.state.currentDate.data[typeName][this.state.selectItemIndex].date
        // this.state.currentTime = this.state.currentYear + '年' + dates;
        // let emitTime = {
        //     year: this.state.currentYear,
        //     msg: dates == '全年' ? '': dates
        // }
        // if(this.state.platFormType == 'netfood'){
        //     sessionStorage.setItem('netfoodTime', JSON.stringify(emitTime));
        // }
        // if(this.state.platFormType == 'foodWaste'){
        //     sessionStorage.setItem('foodWasteTime', JSON.stringify(emitTime));
        // }
        // this.state.$emit("timeChange", emitTime);
        
    }
     
    componentDidMount(){
        this.init()
    }
    render(){
        const content = (
            <div className="">
                <div className="date-container">
                    <div className="date-box">
                        <div className="date-type">
                            <span onClick={this.changeDateType.bind(this,1)} className={this.state.dateType === 1 ? 'item active' : 'item' }>月度</span>
                            <span onClick={this.changeDateType.bind(this,4)} className={this.state.dateType === 4 ? 'item active' : 'item' }>年</span>
                        </div>
                         <div className="date-year">
                            <span onClick={this.changeYear.bind(this,'prev')} className={this.state.currentIndex >= (this.state.originDate.length-1) ? 'item prev-year disabled' : ''}>上一年</span>
                            <span className="item current-year">{ this.state.currentYear }</span>
                            <span onClick={this.changeYear.bind(this,'next')} className={this.state.currentIndex <= 0 ? 'item next-year disabled' : ''}>下一年</span>
                        </div>
                        {/* <DateTimebox currentDate={this.state.currentDate} dateType={this.state.dateType}/> */}
                        {
                            this.state.currentDate && 
                            <div className="date-item-box">123</div>
                        }
                        {/* <div className="date-item-box" v-show="currentDate.data">
                            日期类型 
                            <div className="type-month" v-show="dateType === 1">
                                <span className="item" v-for="(item, index) in currentDate.data.month" :key="index" :className="{'disabled' : !item.mark, 'active' : index === selectItemIndex}" onClick="changeItemStatus(item,index)">{{ item.date }}</span>
                            </div>
                            <div className="type-allyear" v-show="dateType === 4">
                                <span className="item" v-for="(item, index) in currentDate.data.allYear" :key="index" :className="{'disabled' : !item.mark, 'active' : index === selectItemIndex}" onClick="changeItemStatus(item,index)">{{ item.date }}</span>
                            </div>
                        </div> */}
                        {/*
                        <div className="date-footer">
                            <div className="left">{{ currentTime }}</div>
                            <div className="right">
                                <span className="btn cancel" onClick="cancel()">取消</span>
                                <span className="btn ok" onClick="confirmDate()">确定</span>
                            </div>
                        </div> */}
                    </div>
                </div>
            </div>
        )
        return (
            <div className="dateSelect">
            <Popover placement="bottomLeft" content={content} title="" trigger="click" className="dateContainer">
                <Button>Click</Button>
            </Popover>
            </div>
        );
    }
}
